---
version: '3.3'

services:
  main:
    container_name: extract_cookie
    build:
      context: ./extract_cookie
      dockerfile: Dockerfile
    command: python3 -u main.py
    depends_on:
      chrome:
        condition: service_healthy
    volumes:
      - ./extract_cookie:/app
    
  chrome:
    image: selenium/standalone-chrome:108.0
    ports:
      - '8888:4444'
    privileged: true
    shm_size: 2g
    healthcheck:
      test: ["CMD", "curl", "--fail", "chrome:4444/ui"]
      interval: 5s
      retries: 10
    environment:
      - SE_NODE_SESSION_TIMEOUT=99999
